# Reusable job to run a PowerShell script and publish outputs
parameters:
  variableGroup: ''
  displayName: ''
  scriptPath: ''
  workingDir: ''
  arguments: ''
  artifactName: ''
  publishPath: ''
  ensureAz: false

  # Agent control
  poolType: 'hosted'      # hosted | self
  poolName: ''            # required when poolType=self

  # Optional capability-based routing
  adh_group: ''
  adh_subscription_type: ''   # prd | nonprd

jobs:
- job: run_powershell
  displayName: ${{ parameters.displayName }}

  # Agent selection
  ${{ if eq(parameters.poolType, 'hosted') }}:
    pool:
      vmImage: 'windows-latest'
  ${{ if ne(parameters.poolType, 'hosted') }}:
    pool:
      name: ${{ parameters.poolName }}
      ${{ if and(ne(parameters.adh_group, ''), ne(parameters.adh_subscription_type, '')) }}:
        demands:
        - ${{ format('custodian -equals {0}_{1}', parameters.adh_group, parameters.adh_subscription_type) }}

  variables:
  - group: ${{ parameters.variableGroup }}

  steps:
  - checkout: self

  - ${{ if eq(parameters.ensureAz, true) }}:
    - task: PowerShell@2
      displayName: 'Ensure Az modules'
      inputs:
        pwsh: true
        targetType: inline
        script: |
          Install-Module Az -Scope CurrentUser -Force -AllowClobber
          Get-Module Az.Accounts,Az.Resources,Az.KeyVault -ListAvailable | Select-Object Name,Version

  - task: PowerShell@2
    displayName: Prepare output folder
    inputs:
      targetType: inline
      pwsh: true
      script: |
        $out = "${{ parameters.publishPath }}"
        if ([string]::IsNullOrWhiteSpace($out)) { throw "publishPath parameter is empty." }
        if (-not (Test-Path -LiteralPath $out)) { New-Item -ItemType Directory -Path $out -Force | Out-Null }
        Write-Host "Prepared: $out"

  - task: PowerShell@2
    displayName: Run ${{ parameters.scriptPath }}
    inputs:
      targetType: filePath
      filePath: ${{ parameters.scriptPath }}
      workingDirectory: ${{ parameters.workingDir }}
      arguments: ${{ parameters.arguments }}
      pwsh: true
      failOnStderr: true

  - task: PowerShell@2
    displayName: List publish dir
    inputs:
      targetType: inline
      pwsh: true
      script: |
        $out = "${{ parameters.publishPath }}"
        if (Test-Path -LiteralPath $out) {
          Get-ChildItem -Recurse -Force $out | Format-Table -AutoSize
        } else {
          Write-Warning "Publish path missing: $out"
          New-Item -ItemType Directory -Path $out -Force | Out-Null
          Set-Content -Path (Join-Path $out 'README.txt') -Value 'No output files were produced.'
        }

  - task: PublishBuildArtifacts@1
    displayName: Publish artifact
    inputs:
      PathtoPublish: ${{ parameters.publishPath }}
      ArtifactName: ${{ parameters.artifactName }}
