parameters:
  run_mode: 'ByCustodian'
  adh_group: ''
  adh_subscription_type: ''        # prd | nonprd
  secretsCsvPath: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/kv-secrets'
  branchName: ''
  poolType: 'hosted'
  poolName: ''

- stage: KV_Secrets
  displayName: >-
    KV Secrets (${{
      format('{0}{1}',
        parameters.run_mode,
        if(eq(parameters.run_mode,'ByCustodian'), format(':{0}', parameters.adh_group), '')
      )
    }})

  variables:
    outDir: ${{ parameters.outDir }}

  jobs:
  - ${{ if eq(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'KV Secrets Scan (ByCustodian)'
        scriptPath: 'sanitychecks/scripts/Scan-KV-Secrets-ByCustodian.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -SecretCsvPath "${{ parameters.secretsCsvPath }}"
          -adh_group "${{ parameters.adh_group }}"
          -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "kv-secrets"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        adh_group: ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}

  - ${{ if ne(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'KV Secrets Scan (AllADH)'
        scriptPath: 'sanitychecks/scripts/Scan-KV-Secrets-AllADH.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -SecretCsvPath "${{ parameters.secretsCsvPath }}"
          -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "kv-secrets-ALLADH"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        adh_group: ''
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
