parameters:
  adh_group: ''
  adh_subscription_type: ''        # prd | nonprd
  prodCsvPath: ''
  nonProdCsvPath: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-perms'
  branchName: ''
  poolType: 'self'                 # hosted | self
  poolSuffix: '_agent1'
  poolName: ''                     # leave empty to compute
  useDemands: true

stages:
- stage: RG_Permissions_ByCustodian
  displayName: "RG Permissions – ${{ parameters.adh_group }}"
  variables:
    outDir: ${{ parameters.outDir }}

  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      variableGroup: ${{ parameters.variableGroup }}
      displayName: 'RG Permissions Scan (ByCustodian)'
      scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
      workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
      arguments: >
        -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
        -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
        -adh_group "${{ parameters.adh_group }}" -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
      artifactName: 'rg-perms'
      publishPath: '$(outDir)'
      poolType: ${{ parameters.poolType }}
      poolName: ${{ parameters.poolName }}
      poolSuffix: ${{ parameters.poolSuffix }}
      adh_group: ${{ parameters.adh_group }}
      adh_subscription_type: ${{ parameters.adh_subscription_type }}
      useDemands: ${{ parameters.useDemands }}
