parameters:
  run_mode: 'AllADH'               # ByCustodian | AllADH
  adh_group: ''
  adh_subscription_type: 'nonprd'  # prd | nonprd
  prodCsvPath: ''
  nonProdCsvPath: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-perms'
  branchName: ''
  poolType: 'self'                 # hosted | self
  poolSuffix: '_agent1'            # used only if poolName is empty
  poolName: ''                     # explicit agent name (optional)
  useDemands: false                # capability demands (usually false for AllADH)

- stage: RG_Permissions
  displayName: >-
    RG Permissions (${{
      format('{0}{1}',
        parameters.run_mode,
        if(eq(parameters.run_mode,'ByCustodian'), format(':{0}', parameters.adh_group), '')
      )
    }})

  variables:
    outDir: ${{ parameters.outDir }}

  jobs:
  # ------- ByCustodian -------
  - ${{ if eq(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions – ByCustodian'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -adh_group "${{ parameters.adh_group }}" -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-perms"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        poolSuffix: ${{ parameters.poolSuffix }}
        adh_group: ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        useDemands: ${{ parameters.useDemands }}

  # ------- AllADH -------
  - ${{ if ne(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions – ALLADH'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-AllADH.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-perms-ALLADH"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        poolSuffix: ${{ parameters.poolSuffix }}
        adh_group: ''  # not used
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        useDemands: false
