# RG Permissions (ByCustodian | AllADH)
parameters:
  run_mode: 'ByCustodian'          # ByCustodian | AllADH
  adh_group: ''
  adh_subscription_type: ''        # prd | nonprd
  prodCsvPath: ''
  nonProdCsvPath: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-perms'
  branchName: ''
  poolType: 'hosted'               # hosted | self
  poolPrefix: ''                   # unused here (kept for symmetry)
  poolSuffix: ''                   # e.g. _agent1 | _agent2
  poolName: ''                     # explicit override (AllADH fixed pools)

- stage: RG_Permissions
  displayName: >-
    RG Permissions (${{
      format('{0}{1}',
        parameters.run_mode,
        if(eq(parameters.run_mode, 'ByCustodian'), format(':{0}', parameters.adh_group), '')
      )
    }})

  variables:
    outDir: ${{ parameters.outDir }}

  jobs:
  # ByCustodian
  - ${{ if eq(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions (ByCustodian)'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)"
          -ClientId "$(backend_client_id)"
          -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}"
          -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -adh_group "${{ parameters.adh_group }}"
          -OutputDir "$(outDir)"
          -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-perms"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        # Self-hosted: poolName = adh_group + '_' + adh_subscription_type + poolSuffix
        poolSuffix: ${{ parameters.poolSuffix }}
        adh_group: ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}

  # AllADH
  - ${{ if ne(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions (AllADH)'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-AllADH.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)"
          -ClientId "$(backend_client_id)"
          -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}"
          -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -OutputDir "$(outDir)"
          -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-perms-ALLADH"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        # For AllADH, pass explicit fixed pool names from pipeline.yml
        poolName: ${{ parameters.poolName }}
        adh_group: ''
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
