parameters:
  run_mode: 'ByCustodian'
  adh_group: ''
  adh_subscription_type: ''         # prd | nonprd
  prodCsvPath: ''
  nonProdCsvPath: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-perms'
  branchName: ''
  poolType: 'hosted'
  poolPrefix: ''                    # optional
  poolSuffix: ''                    # e.g., '_agent1' or '_agent2'
  poolName: ''                      # direct override when poolType=self

stages:
- ${{ if eq(parameters.run_mode, 'ByCustodian') }}:
  - stage: RG_Permissions_ByCustodian
    displayName: "RG Permissions (ByCustodian)"
    variables: { outDir: ${{ parameters.outDir }} }
    jobs:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions Scan (ByCustodian)'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -adh_group "${{ parameters.adh_group }}" -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-perms"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ coalesce(parameters.poolName, format('{0}{1}_{2}{3}', parameters.poolPrefix, parameters.adh_group, parameters.adh_subscription_type, parameters.poolSuffix)) }}
        adh_group: ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}

- ${{ if ne(parameters.run_mode, 'ByCustodian') }}:
  - stage: RG_Permissions_AllADH
    displayName: "RG Permissions (All ADH)"
    variables: { outDir: ${{ parameters.outDir }} }
    jobs:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions Scan (AllADH)'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-AllADH.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-perms-ALLADH"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        adh_group: ''
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
