parameters:
  run_mode: 'ByCustodian'
  adh_group: ''
  adh_subscription_type: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-tags'
  branchName: ''
  poolType: 'hosted'
  poolPrefix: ''
  poolSuffix: ''
  poolName: ''

stages:
- ${{ if eq(parameters.run_mode, 'ByCustodian') }}:
  - stage: RG_Tags_ByCustodian
    displayName: "RG Tags (ByCustodian)"
    variables: { outDir: ${{ parameters.outDir }} }
    jobs:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Tags Scan (ByCustodian)'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Tags.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -adh_group "${{ parameters.adh_group }}" -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-tags"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ coalesce(parameters.poolName, format('{0}{1}_{2}{3}', parameters.poolPrefix, parameters.adh_group, parameters.adh_subscription_type, parameters.poolSuffix)) }}
        adh_group: ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}

- ${{ if ne(parameters.run_mode, 'ByCustodian') }}:
  - stage: RG_Tags_AllADH
    displayName: "RG Tags (All ADH)"
    variables: { outDir: ${{ parameters.outDir }} }
    jobs:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Tags Scan (AllADH)'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Tags.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ScanAll -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
        artifactName: "rg-tags-ALLADH"
        publishPath: "$(outDir)"
        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        adh_group: ''
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
