parameters:
  adh_subscription_type: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-tags'
  branchName: ''
  poolType: 'self'
  poolName: ''
  poolSuffix: '_agent1'
  useDemands: false

stages:
- stage: RG_Tags_AllADH
  displayName: "RG Tags – ALLADH"
  variables:
    outDir: ${{ parameters.outDir }}
  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      variableGroup: ${{ parameters.variableGroup }}
      displayName: 'RG Tags Scan (AllADH)'
      scriptPath: 'sanitychecks/scripts/Scan-RG-Tags.ps1'
      workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
      arguments: >
        -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
        -ScanAll -OutputDir "$(outDir)" -BranchName "${{ parameters.branchName }}"
      artifactName: 'rg-tags-ALLADH'
      publishPath: '$(outDir)'
      poolType: ${{ parameters.poolType }}
      poolName: ${{ parameters.poolName }}
      poolSuffix: ${{ parameters.poolSuffix }}
      adh_group: ''
      adh_subscription_type: ${{ parameters.adh_subscription_type }}
      useDemands: ${{ parameters.useDemands }}
